### PR TITLE
perf: rolescmd with -counts option

### PR DESCRIPTION
**Pull request by almeidx**
Current setup:
image

With this pr:
image

***

Why the current implementation is slow:
- It uses [`<Role>#members`](https://github.com/discordjs/discord.js/blob/stable/src/structures/Role.js#L139), which by itself uses [`<GuildMember>#roles#cache`](https://github.com/discordjs/discord.js/blob/stable/src/managers/GuildMemberRoleManager.js#L34)

### CODE REVIEW

**Comment by almeidx** [comment]
Alternatively, we could get rid of the map and increment the `_memberCount` property instead but we would have to `@ts-expect-error` on it since the property doesn't actually exist in the typings

Throughts @Dragory? 

image

**Comment by Dragory** [comment]
I would definitely prefer using a Map so we don't pollute the role objects.

**Comment by almeidx** [comment]
The current implementation does both. I'll change it to not pollute the role objects then

**Comment by Dragory** [comment]
Thank you for the PR!

**Pull request merged**
